export const fakerRulesMapping = {
	'location.buildingNumber': ['buildingNumber'],
	'location.cardinalDirection': ['cardinalDirection'],
	'location.city': ['city'],
	'location.cityName': ['cityName'],
	'location.country': ['country'],
	'location.countryCode': ['countryCode'],
	'location.county': ['county', 'district'],
	'location.direction': ['direction'],
	'location.latitude': ['latitude', 'lat'],
	'location.longitude': ['longitude', 'lng', 'long'],
	'location.nearbyGPSCoordinate': ['nearbyGPSCoordinate'],
	'location.ordinalDirection': ['ordinalDirection'],
	'location.secondaryAddress': ['secondarylocation'],
	'location.state': ['state'],
	'location.stateAbbr': ['stateAbbr'],
	'location.street': ['street'],
	'location.streetAddress': ['streetAddress', 'address', 'location'],
	'location.streetName': ['streetName', 'street'],
	'location.timeZone': ['timeZone'],
	'location.zipCode': ['zipCode', 'postal', 'zip'],
	'address.zipCodeByState': ['zipCodeByState'],
	'animal.bear': ['bear'],
	'animal.bird': ['bird'],
	'animal.cat': ['cat'],
	'animal.cetacean': ['cetacean'],
	'animal.cow': ['cow'],
	'animal.crocodilia': ['crocodilia'],
	'animal.dog': ['dog'],
	'animal.fish': ['fish'],
	'animal.horse': ['horse'],
	'animal.insect': ['insect'],
	'animal.lion': ['lion'],
	'animal.rabbit': ['rabbit'],
	'animal.rodent': ['rodent'],
	'animal.snake': ['snake'],
	'animal.type': ['type'],
	'color.cmyk': ['cmyk'],
	'color.colorByCSSColorSpace': ['colorByCSSColorSpace'],
	'color.cssSupportedFunction': ['cssSupportedFunction'],
	'color.cssSupportedSpace': ['cssSupportedSpace'],
	'color.hsl': ['hsl'],
	'color.human': ['human'],
	'color.hwb': ['hwb'],
	'color.lab': ['lab'],
	'color.lch': ['lch'],
	'color.rgb': ['rgb'],
	'color.space': ['space'],
	'commerce.department': ['department'],
	'commerce.price': ['price'],
	'commerce.product': ['product'],
	'commerce.productAdjective': ['productAdjective'],
	'commerce.productDescription': ['productDescription'],
	'commerce.productMaterial': ['productMaterial'],
	'commerce.productName': ['productName', 'product_name'],
	'company.bs': ['bs'],
	'company.bsAdjective': ['bsAdjective'],
	'company.bsBuzz': ['bsBuzz'],
	'company.bsNoun': ['bsNoun'],
	'company.catchPhrase': ['catchPhrase'],
	'company.catchPhraseAdjective': ['catchPhraseAdjective'],
	'company.catchPhraseDescriptor': ['catchPhraseDescriptor'],
	'company.catchPhraseNoun': ['catchPhraseNoun'],
	'company.companySuffix': ['companySuffix'],
	'company.name': ['companyName', 'company_name', 'company'],
	'company.suffixes': ['suffixes'],
	'database.collation': ['collation'],
	'database.column': ['column'],
	'database.engine': ['engine'],
	'database.mongodbObjectId': ['mongodbObjectId'],
	'database.type': ['type'],
	'datatype.array': ['array'],
	'datatype.bigInt': ['bigInt'],
	'datatype.boolean': ['boolean', 'is'],
	'datatype.datetime': ['datetime'],
	'datatype.float': ['float'],
	'datatype.hexadecimal': ['hexadecimal'],
	'datatype.json': ['json'],
	'datatype.string': ['string'],
	'datatype.uuid': ['uuid'],
	'date.between': ['between'],
	'date.betweens': ['betweens'],
	'date.birthdate': ['birthdate'],
	'date.future': ['future'],
	'date.month': ['month'],
	'date.past': ['past', 'createdDate', 'updatedDate'],
	'date.recent': ['recent'],
	'date.soon': ['soon'],
	'date.weekday': ['weekday'],
	'finance.account': ['account'],
	'finance.accountName': ['accountName'],
	'finance.amount': ['amount'],
	'finance.bic': ['bic'],
	'finance.bitcoinAddress': ['bitcoinAddress'],
	'finance.creditCardCVV': ['creditCardCVV'],
	'finance.creditCardIssuer': ['creditCardIssuer'],
	'finance.creditCardNumber': ['creditCardNumber', 'creditcard'],
	'finance.currencyCode': ['currencyCode', 'currency'],
	'finance.currencyName': ['currencyName'],
	'finance.currencySymbol': ['currencySymbol'],
	'finance.ethereumAddress': ['ethereumAddress'],
	'finance.iban': ['iban'],
	'finance.litecoinAddress': ['litecoinAddress'],
	'finance.mask': ['mask'],
	'finance.pin': ['pin'],
	'finance.routingNumber': ['routingNumber'],
	'finance.transactionDescription': ['transactionDescription'],
	'finance.transactionType': ['transactionType'],
	'git.branch': ['branch'],
	'git.commitEntry': ['commitEntry'],
	'git.commitMessage': ['commitMessage'],
	'git.commitSha': ['commitSha'],
	'git.shortSha': ['shortSha'],
	'hacker.abbreviation': ['abbreviation'],
	'hacker.adjective': ['adjective'],
	'hacker.ingverb': ['ingverb'],
	'hacker.noun': ['noun'],
	'hacker.phrase': ['phrase'],
	'hacker.verb': ['verb'],
	'helpers.arrayElement': ['arrayElement'],
	'helpers.arrayElements': ['arrayElements'],
	'helpers.fake': ['fake'],
	'helpers.maybe': ['maybe'],
	'helpers.mustache': ['mustache'],
	'helpers.objectKey': ['objectKey'],
	'helpers.objectValue': ['objectValue'],
	'helpers.regexpStyleStringParse': ['regexpStyleStringParse'],
	'helpers.replaceCreditCardSymbols': ['replaceCreditCardSymbols'],
	'helpers.replaceSymbolWithNumber': ['replaceSymbolWithNumber'],
	'helpers.replaceSymbols': ['replaceSymbols'],
	'helpers.shuffle': ['shuffle'],
	'helpers.slugify': ['slugify'],
	'helpers.unique': ['unique'],
	'helpers.uniqueArray': ['uniqueArray'],
	'image.abstract': ['abstract'],
	'image.animals': ['animals'],
	'image.avatar': ['avatar'],
	'image.business': ['business'],
	'image.cats': ['cats'],
	'image.city': ['city'],
	'image.dataUri': ['dataUri'],
	'image.fashion': ['fashion'],
	'image.food': ['food'],
	'image.image': ['image'],
	'image.imageUrl': ['imageUrl'],
	'image.nature': ['nature'],
	'image.nightlife': ['nightlife'],
	'image.people': ['people'],
	'image.sports': ['sports'],
	'image.technics': ['technics'],
	'image.transport': ['transport'],
	'internet.avatar': ['avatar'],
	'internet.color': ['color'],
	'internet.domainName': ['domainName', 'domain'],
	'internet.domainSuffix': ['domainSuffix'],
	'internet.domainWord': ['domainWord'],
	'internet.email': ['email'],
	'internet.emoji': ['emoji'],
	'internet.exampleEmail': ['exampleEmail', 'email'],
	'internet.httpMethod': ['httpMethod'],
	'internet.httpStatusCode': ['httpStatusCode'],
	'internet.ip': ['ip'],
	'internet.ipv4': ['ipv4'],
	'internet.ipv6': ['ipv6'],
	'internet.mac': ['mac'],
	'internet.password': ['password'],
	'internet.port': ['port'],
	'internet.protocol': ['protocol'],
	'internet.url': ['url', 'link'],
	'internet.userAgent': ['userAgent'],
	'internet.userName': ['userName', 'createdBy'],
	'lorem.lines': ['lines'],
	'lorem.paragraph': ['paragraph'],
	'lorem.paragraphs': ['paragraphs'],
	'lorem.sentence': ['sentence'],
	'lorem.sentences': ['sentences'],
	'lorem.slug': ['slug'],
	'lorem.text': ['text', 'description'],
	'lorem.word': ['word'],
	'lorem.words': ['words'],
	'music.genre': ['genre'],
	'music.songName': ['songName'],
	'name.firstName': ['firstName', 'first_name'],
	'name.fullName': ['fullName', 'name', 'full_name'],
	'name.gender': ['gender'],
	'name.jobArea': ['jobArea'],
	'name.jobDescriptor': ['jobDescriptor'],
	'name.jobTitle': ['jobTitle'],
	'name.jobType': ['jobType'],
	'name.lastName': ['lastName'],
	'name.middleName': ['middleName'],
	'name.prefix': ['prefix'],
	'name.sex': ['sex'],
	'name.sexType': ['sexType', 'gender'],
	'name.suffix': ['suffix'],
	'phone.imei': ['imei'],
	'phone.number': ['phoneNumber', 'phone_number', 'phone', 'mobile', 'telephone'],
	'random.alpha': ['alpha'],
	'random.alphaNumeric': ['alphaNumeric'],
	'random.locale': ['locale'],
	'random.numeric': ['numeric'],
	'random.word': ['word'],
	'random.words': ['words'],
	'science.chemicalElement': ['chemicalElement'],
	'science.unit': ['unit'],
	'system.commonFileExt': ['commonFileExt', 'extension'],
	'system.commonFileName': ['commonFileName', 'file_name', 'filename'],
	'system.commonFileType': ['commonFileType'],
	'system.cron': ['cron'],
	'system.directoryPath': ['directoryPath'],
	'system.fileExt': ['fileExt'],
	'system.fileName': ['fileName'],
	'system.filePath': ['filePath'],
	'system.fileType': ['fileType'],
	'system.mimeType': ['mimeType'],
	'system.networkInterface': ['networkInterface'],
	'system.semver': ['semver'],
	'vehicle.bicycle': ['bicycle'],
	'vehicle.color': ['color'],
	'vehicle.fuel': ['fuel'],
	'vehicle.manufacturer': ['manufacturer'],
	'vehicle.model': ['model'],
	'vehicle.type': ['type'],
	'vehicle.vehicle': ['vehicle'],
	'vehicle.vin': ['vin'],
	'vehicle.vrm': ['vrm'],
	'word.adjective': ['adjective'],
	'word.adverb': ['adverb'],
	'word.conjunction': ['conjunction'],
	'word.interjection': ['interjection'],
	'word.noun': ['noun'],
	'word.preposition': ['preposition'],
	'word.verb': ['verb'],
	'cust.quote': ['quote'],
	'cus.phrase': ['phrase'],
	'movie.movie': ['movie'],
	'movie.movieCharacter': ['movieCharacter'],
	'sports.americanFootballTeam': ['americanFootballTeam'],
	'sports.baseballTeam': ['baseballTeam'],
	'sports.basketballTeam': ['basketballTeam'],
	'sports.footballTeam': ['footballTeam', 'team'],
	'sports.iceHockeyTeam': ['iceHockeyTeam'],
	'sports.sports': ['sports', 'sport'],
	'sports.sportsTeam': ['sportsTeam'],
	'airports.randAirline': ['randAirline', 'airline'],
	'airports.randAirport': ['randAirport', 'airport'],
	'airports.randAirportCode': ['randAirportCode', 'airportCode'],
	'airports.randAirportName': ['randAirportName', 'airport'],
	'airports.randFlightDetails': ['randFlightDetails'],
	'airports.randFlightNumber': ['randFlightNumber', 'flightNumber'],
	'airports.randSeatNumber': ['randSeatNumber', 'seatNumber'],
	'helpers.incrementalDate': ['incrementalDate', 'date', 'time'],
	'datatype.number': [
		'number',
		'no',
		'total',
		'version',
		'count',
		'rating',
		'length',
		'rate',
		'quantity',
		'amount',
		'price',
		'weight',
		'size',
		'width',
		'height',
		'depth',
		'age',
		'limit',
		'code',
		'id',
	],
};
